/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.init;

import org.junit.Test;

import static org.junit.Assert.*;

public class RectangleTest {
    @Test
    public void testSomeLibraryMethod() {
        Rectangle classUnderTest = new Rectangle();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
